steps:
  # Step 1: Get cluster credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials prompt-cluster --region=europe-central2 &&
        kubectl apply -f k8s/deployment.yaml -f k8s/service.yaml

timeout: 600s
