steps:
  # Authenticate and configure access to GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials prompt-cluster --region=europe-central2

  # Deploy using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'apply',
        '-f', 'k8s/deployment.yaml',
        '-f', 'k8s/service.yaml'
      ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=europe-central2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=prompt-cluster'

timeout: 600s
